GET http://127.0.0.1:5000/goods

###

GET http://127.0.0.1:5000/shops

###

POST http://127.0.0.1:5000/shops
Content-Type: application/json

{
    "name": "McDonald's"
}


###
POST http://127.0.0.1:5000/goods
Content-Type: application/json

{
    "name": "Hamburger",
    "shop": "647f38fc46087784a13e6954",
    "imageName": "hamburger.jpg",
    "price": 10
}

###

PATCH http://127.0.0.1:5000/goods
Content-Type: application/json

{
    "id": "647f3e080053982e92e07e17",
    "price": 20
}

###
GET http://127.0.0.1:5000/orders


###
POST http://127.0.0.1:5000/orders
Content-Type: application/json

{
    "username": "Ivan",
    "email": "ivan@gmail.com",
    "phone": "0681386000",
    "address": "Kharkiv",
    "goods": [{
        "_id": "6481f86c41d9dd88ee0a97df",
    }]
}